# -*- coding: utf-8 -*-
"""csv.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xsFkHzZWrW2tov1RMv7543b1ylQCSv4k
"""

import pandas as pd
import numpy as np

data= {
    'Patient_ID':['P001','P002','P003','P004','P005','P006'],
    'Name':['Vijay', 'Ajay', 'Kiran', 'Amith', 'Suresh',None],
    'Department':['Carona','Cancer','Neurology','Cardiology','Cancer','ICU'],
    'Admission_Date': ['2025-01-15', '2025-02-10', '2025-03-03','2025-01-22','2025-04-06','2025-08-04'],
    'Bill':[7000.80,76000.00,10000.00,200000.00,80000,None]
}
df = pd.DataFrame(data)
df.to_csv('hospital_data.csv', index=False)
print("Created data successfully...")

